#!/usr/bin/python
from toggl_driver import TogglDriver

import sys

def main(args):
    """ Run the main file """
    TogglDriver('toggl').run(args)

if __name__ == "__main__":
	main(sys.argv[1:])